" Standard vim options
set backspace=2           " allow backspacing over everything in insert mode
set diffopt=filler,iwhite " keep files synced and ignore whitespace
"   set foldcolumn=2          " set a column incase we need it
"   set foldlevel=0           " show contents of all folds
"   set foldmethod=indent     " use indent unless overridden
set guioptions-=m         " Remove menu from the gui
set guioptions-=T         " Remove toolbar
set hidden                " hide buffers instead of closing
set history=50            " keep 50 lines of command line history
set ignorecase            " Do case insensitive matching
set incsearch             " Incremental search
set laststatus=2          " always have status bar
set linebreak             " This displays long lines as wrapped at wordboundries
set matchtime=10          " Time to flash the brack with showmatch
set nobackup              " Don't keep a backup file
set nocompatible          " Use Vim defaults (much better!)
set nofen                 " disable folds
set notimeout             " i like to be pokey
set ttimeout              " timeout on key-codes
set ttimeoutlen=100       " timeout on key-codes after 100ms
set ruler                 " the ruler on the bottom is useful
set scrolloff=1           " dont let the curser get too close to the edge
set showcmd               " Show (partial) command in status line.
set showmatch             " Show matching brackets.
set textwidth=0           " Don't wrap words by default
set textwidth=80          " This wraps a line with a break when you reach80 chars
set virtualedit=block     " let blocks be in virutal edit mode
set wildmenu              " This is used with wildmode(full) to cycle options

" VIM Color options
set background=dark 
colorscheme solarized 
syntax on

" Indentation
set autoindent            " always set autoindenting on
set smartindent
set cindent               " c code indenting
set expandtab             " Get rid of tabs altogether and replace with spaces
set shiftwidth=4          " Set indention level to be the same as softtabstop
set softtabstop=4         " Why are tabs so big?  This fixes it
filetype plugin indent on " Enable VIM indenting for XML

" Spell checking
autocmd BufNewFile,BufRead *.git/COMMIT_EDITMSG set spell
"
" VIM Color options
   set background=dark 
   colorscheme ir_black 
   syntax on

" Powerline
    set rtp+=~/.env/powerline/powerline/bindings/vim
